# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Fast-API CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test python Code
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest
          cd app/
          pytest

  build-push-container:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build -t patricken/fast-api:${GITHUB_SHA} .
          docker tag  patricken/fast-api:${GITHUB_SHA} patricken/fast-api:latest
          docker images
          docker run -d -p 80:80 --name fastapi patricken/fast-api:${GITHUB_SHA}
          sleep 10
          docker login -u ${{ secrets.REGISTRY_USER  }} -p ${{ secrets.REGISTRY_PASSWD  }}
          docker push patricken/fast-api:${GITHUB_SHA}
          docker push patricken/fast-api:latest

  deploy:
    needs: build-push-container
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST  }}
          username: ${{ secrets.SERVER_USER  }}
          key: ${{ secrets.SERVER_SSH_KEY  }}
          port: 22
          script: |
            sudo docker rm -f fastapi 
            sudo docker rmi patricken/fast-api:latest
            sleep 10 
            sudo docker run -d -p 9000:80 --name fastapi patricken/fast-api:latest
            sudo docker ps 
            sleep 10 
            curl localhost:9000
            ls 
            sudo docker images
